const fifaCodesBySlug: Record<string, string> = {
  algeria: "ALG",
  argentina: "ARG",
  australia: "AUS",
  austria: "AUT",
  belgium: "BEL",
  "bosnia-and-herzegovina": "BIH",
  "bosnia-herzegovina": "BIH",
  brazil: "BRA",
  "cabo-verde": "CPV",
  canada: "CAN",
  colombia: "COL",
  "congo-dr": "COD",
  "cote-d-ivoire": "CIV",
  croatia: "CRO",
  curacao: "CUW",
  czechia: "CZE",
  ecuador: "ECU",
  egypt: "EGY",
  england: "ENG",
  france: "FRA",
  germany: "GER",
  ghana: "GHA",
  haiti: "HAI",
  "ir-iran": "IRN",
  iraq: "IRQ",
  japan: "JPN",
  jordan: "JOR",
  "korea-republic": "KOR",
  mexico: "MEX",
  morocco: "MAR",
  netherlands: "NED",
  "new-zealand": "NZL",
  norway: "NOR",
  panama: "PAN",
  paraguay: "PAR",
  portugal: "POR",
  qatar: "QAT",
  "saudi-arabia": "KSA",
  scotland: "SCO",
  senegal: "SEN",
  "south-africa": "RSA",
  spain: "ESP",
  sweden: "SWE",
  switzerland: "SUI",
  tunisia: "TUN",
  turkiye: "TUR",
  uruguay: "URU",
  usa: "USA",
  uzbekistan: "UZB",
};

export function getFifaCode(slug: string) {
  return fifaCodesBySlug[slug] ?? slug.slice(0, 3).toUpperCase();
}

export function allFifaCodes() {
  return [...new Set(Object.values(fifaCodesBySlug))].sort();
}
